export const bankList = [
  { value: '044', name: 'Access Bank' },
  { value: '063', name: 'Access Bank (Diamond)' },
  { value: '035A', name: 'ALAT by WEMA' },
  { value: '401', name: 'ASO Savings and Loans' },
  { value: '50931', name: 'Bowen Microfinance Bank' },
  { value: '50823', name: 'CEMCS Microfinance Bank' },
  { value: '023', name: 'Citibank Nigeria' },
  { value: '050', name: 'Ecobank Nigeria' },
  { value: '562', name: 'Ekondo Microfinance Bank' },
  { value: '50126', name: 'Eyowo' },
  { value: '070', name: 'Fidelity Bank' },
  { value: '011', name: 'First Bank of Nigeria' },
  { value: '214', name: 'First City Monument Bank' },
  { value: '501', name: 'FSDH Merchant Bank Limited' },
  { value: '00103', name: 'Globus Bank' },
  { value: '058', name: 'Guaranty Trust Bank' },
  { value: '51251', name: 'Hackman Microfinance Bank' },
  { value: '50383', name: 'Hasal Microfinance Bank' },
  { value: '030', name: 'Heritage Bank' },
  { value: '51244', name: 'Ibile Microfinance Bank' },
  { value: '301', name: 'Jaiz Bank' },
  { value: '082', name: 'Keystone Bank' },
  { value: '50211', name: 'Kuda Bank' },
  { value: '90052', name: 'Lagos Building Investment Company Plc.' },
  { value: '565', name: 'One Finance' },
  { value: '526', name: 'Parallex Bank' },
  { value: '311', name: 'Parkway - ReadyCash' },
  { value: '076', name: 'Polaris Bank' },
  { value: '101', name: 'Providus Bank' },
  { value: '125', name: 'Rubies MFB' },
  { value: '51310', name: 'Sparkle Microfinance Bank' },
  { value: '221', name: 'Stanbic IBTC Bank' },
  { value: '068', name: 'Standard Chartered Bank' },
  { value: '232', name: 'Sterling Bank' },
  { value: '100', name: 'Suntrust Bank' },
  { value: '302', name: 'TAJ Bank' },
  { value: '51211', name: 'TCF MFB' },
  { value: '102', name: 'Titan Bank' },
  { value: '032', name: 'Union Bank of Nigeria' },
  { value: '033', name: 'United Bank For Africa' },
  { value: '215', name: 'Unity Bank' },
  { value: '566', name: 'VFD Microfinance Bank Limited' },
  { value: '035', name: 'Wema Bank' },
  { value: '057', name: 'Zenith Bank' },
];
